engine: hseb.engine.nixiesearch.nixiesearch.NixiesearchEngine
image: nixiesearch/nixiesearch:0.6.4
dataset: 
  dim: 384
  name: hseb-benchmark/msmarco
  query: "query-all-MiniLM-L6-v2-100K"
  corpus: "corpus-all-MiniLM-L6-v2-100K"
batch_size: 1024
k: 100
experiments:
- tag: test
  index:
    m: [16, 32, 64, 96, 128]
    ef_construction: [32, 64, 96, 128, 160, 192, 224, 256]
    quant: ["float32"]
    k: 100
    kwargs:
      docs_per_segment: [12500]
      heap_size: ["8g"]
  search:
    ef_search: [16, 32, 48, 64, 72, 96, 112, 128]
    filter_selectivity: [10, 90, 100]
