name: Tests

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
    tags: [ '*' ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install uv
      uses: astral-sh/setup-uv@v3
    
    - name: Install dependencies
      run: uv pip install -e .[test] --system
    
    - name: Run tests
      run: pytest

    - name: Run e2e test
      run: python -m hseb --config tests/ci.yml --out ci.json

    - name: Run linting
      run: ruff check
    
    - name: Check formatting
      run: ruff format --check

  publish:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    needs: test
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
    
    - name: Install uv
      uses: astral-sh/setup-uv@v3
    
    - name: Build package
      run: uv build
    
    - name: Publish to PyPI
      run: uv publish
      env:
        UV_PUBLISH_TOKEN: ${{ secrets.PYPI_KEY }}